# Netlify build configuration
[build]
  # The command to run to build your site
  command = "npm install && node ./node_modules/@11ty/eleventy/cmd.cjs"
  
  # The folder that contains the finished site
  publish = "_site"